//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Scripts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Scripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Scripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Repository.Scripts.Scripts", typeof(Scripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into cart_item (cart_id, product_item_id, quantity)
        ///values (@cart_id, @product_item_id, @quantity);.
        /// </summary>
        internal static string AddCartItem {
            get {
                return ResourceManager.GetString("AddCartItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into client (name, address, inn)
        ///values (@name, @address, @inn)
        ///returning id.
        /// </summary>
        internal static string AddClient {
            get {
                return ResourceManager.GetString("AddClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into image (product_id, url)
        ///values (@product_id, @url);.
        /// </summary>
        internal static string AddImages {
            get {
                return ResourceManager.GetString("AddImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into operation (id, date, order_id, description)
        ///values (@id, @date, @order_id, @description);.
        /// </summary>
        internal static string AddOperation {
            get {
                return ResourceManager.GetString("AddOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into operation_detail (id, operation_id, type, amount)
        ///values (@id, @operation_id, @type, @amount);.
        /// </summary>
        internal static string AddOperationDetail {
            get {
                return ResourceManager.GetString("AddOperationDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into orders (id, user_id, create_date, delivery_date, status, type)
        ///values (@id ,@user_id, @create_date, @delivery_date, @status, @type);.
        /// </summary>
        internal static string AddOrder {
            get {
                return ResourceManager.GetString("AddOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into orders_item (id, order_id, product_item_id, quantity)
        ///values (@id, @order_id, @product_item_id, @quantity);.
        /// </summary>
        internal static string AddOrderItem {
            get {
                return ResourceManager.GetString("AddOrderItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into product (name, brand, price, status, factory_id)
        ///values (@name, @brand, @price, @status, @factory_id)
        ///returning id;.
        /// </summary>
        internal static string AddProduct {
            get {
                return ResourceManager.GetString("AddProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into product_item (product_id, color, size, weight, quantity)
        ///values (@product_id, @color, @size, @weight, @quantity);.
        /// </summary>
        internal static string AddProductItem {
            get {
                return ResourceManager.GetString("AddProductItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into product_material (product_id, material_id)
        ///values (@product_id, @material_id);.
        /// </summary>
        internal static string AddProductMaterials {
            get {
                return ResourceManager.GetString("AddProductMaterials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into users (username, password, status, role_id, client_id)
        ///values (@username, @password, @status, @role_id, @client_id).
        /// </summary>
        internal static string AddUser {
            get {
                return ResourceManager.GetString("AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into cart (user_id, create_date)
        ///values (@user_id, @create_date)
        ///returning id;.
        /// </summary>
        internal static string CreateCart {
            get {
                return ResourceManager.GetString("CreateCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete
        ///from cart_item
        ///where id = any (@ids).
        /// </summary>
        internal static string DeleteCartItem {
            get {
                return ResourceManager.GetString("DeleteCartItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete
        ///from product_material
        ///where product_id = @id;.
        /// </summary>
        internal static string DeleteProductMaterials {
            get {
                return ResourceManager.GetString("DeleteProductMaterials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select report_date as Date,
        ///       total_price as TotalPrice,
        ///       items as Items
        ///from generate_report(@id);.
        /// </summary>
        internal static string GenerateReport {
            get {
                return ResourceManager.GetString("GenerateReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select report_date as Date,
        ///       total_price as TotalPrice,
        ///       items as Items
        ///from generate_user_report(@id);.
        /// </summary>
        internal static string GenerateUserReport {
            get {
                return ResourceManager.GetString("GenerateUserReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select id   as Id,
        ///       name as Name
        ///from material.
        /// </summary>
        internal static string GetAllMaterials {
            get {
                return ResourceManager.GetString("GetAllMaterials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select o.id            as Id,
        ///       o.type          as Type,
        ///       o.status        as Status,
        ///       o.create_date   as CreateDate,
        ///       o.delivery_date as DeliveryDate,
        ///       u.username      as Username,
        ///       sum(pri.weight) as TotalWeight,
        ///       sum(od.amount)  as TotalPrice
        ///from orders o
        ///         join users u on u.id = o.user_id
        ///         join orders_item oi on o.id = oi.order_id
        ///         join product_item pri on oi.product_item_id = pri.id
        ///         join operation op on o.id = op.order [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetAllOrders {
            get {
                return ResourceManager.GetString("GetAllOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select id      as Id,
        ///       user_id as UserId
        ///from cart
        ///where user_id = @id.
        /// </summary>
        internal static string GetCartByUserId {
            get {
                return ResourceManager.GetString("GetCartByUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select ci.id     as Id,
        ///       pri.id    as ProductItemId,
        ///       p.name    as ProductName,
        ///       p.price   as Price,
        ///       pri.color as Color,
        ///       pri.size as Size,
        ///       ci.quantity as SelectCount,
        ///       ci.is_selected as IsSelected
        ///from cart_item ci
        ///    join product_item pri
        ///on ci.product_item_id = pri.id
        ///    join product p on pri.product_id = p.id
        ///where ci.cart_id = @id;.
        /// </summary>
        internal static string GetCartItemByCartId {
            get {
                return ResourceManager.GetString("GetCartItemByCartId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select id  as Id,
        ///       url as Url
        ///from image
        ///where product_id = @id;.
        /// </summary>
        internal static string GetImagesByProductId {
            get {
                return ResourceManager.GetString("GetImagesByProductId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select o.id            as Id,
        ///       o.type          as Type,
        ///       o.status        as Status,
        ///       o.create_date   as CreateDate,
        ///       o.delivery_date as DeliveryDate,
        ///       u.username      as Username,
        ///       sum(pri.weight) as TotalWeight,
        ///       sum(od.amount)  as TotalPrice
        ///from orders o
        ///         join users u on u.id = o.user_id
        ///         join orders_item oi on o.id = oi.order_id
        ///         join product_item pri on oi.product_item_id = pri.id
        ///         join operation op on o.id = op.order [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetOrdersByUserId {
            get {
                return ResourceManager.GetString("GetOrdersByUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select id         as Id,
        ///       product_id as ProductId,
        ///       color      as Color,
        ///       size       as Size,
        ///       weight     as Weight
        ///from product_item
        ///where id = any(@ids);.
        /// </summary>
        internal static string GetProductItemByIds {
            get {
                return ResourceManager.GetString("GetProductItemByIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select id         as Id,
        ///       product_id as ProductId,
        ///       color      as Color, 
        ///       size       as Size, 
        ///       weight     as Weight
        ///from product_item
        ///where product_id = @id;.
        /// </summary>
        internal static string GetProductItemsByProductId {
            get {
                return ResourceManager.GetString("GetProductItemsByProductId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select m.id   as Id,
        ///       m.name as Name
        ///from product_material pm
        ///         join material m on pm.material_id = m.id
        ///where pm.product_id = @id;.
        /// </summary>
        internal static string GetProductMaterials {
            get {
                return ResourceManager.GetString("GetProductMaterials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select p.id     as Id,
        ///       c.id     as FactoryId,
        ///       c.name   as FactoryName,
        ///       p.brand  as Brand,
        ///       p.name   as Name,
        ///       p.price  as Price,
        ///       p.status as Status
        ///from product p
        ///         join client c on c.id = p.factory_id;.
        /// </summary>
        internal static string GetProducts {
            get {
                return ResourceManager.GetString("GetProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select p.id     as Id,
        ///       c.id     as FactoryId,
        ///       c.name   as FactoryName,
        ///       p.brand  as Brand,
        ///       p.name   as Name,
        ///       p.price  as Price,
        ///       p.status as Status
        ///from product p
        ///         join client c on c.id = p.factory_id
        ///where c.id = @id;.
        /// </summary>
        internal static string GetProductsByFactoryId {
            get {
                return ResourceManager.GetString("GetProductsByFactoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select p.id               as Id,
        ///       c.id               as FactoryId,
        ///       c.name             as FactoryName,
        ///       p.brand            as Brand,
        ///       p.name             as Name,
        ///       p.price            as Price,
        ///       p.status           as Status,
        ///       count(oi.quantity) as TotalBuy
        ///from product p
        ///         join client c on c.id = p.factory_id
        ///         left join product_item pri on pri.product_id = p.id
        ///         left join orders_item oi on oi.product_item_id = pri.id
        ///group by p.id, c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetProductsByTopSell {
            get {
                return ResourceManager.GetString("GetProductsByTopSell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select u.id       as Id,
        ///       u.username as Username,
        ///       u.password as Password,
        ///       r.name     as Role,
        ///       c.id       as ClientId,
        ///       c.name     as Name,
        ///       c.address  as Address,
        ///       c.inn      as INN,
        ///       u.status   as Status
        ///from users u
        ///         join client c on c.id = u.client_id
        ///         join role r on r.id = u.role_id
        ///where u.id = @id
        ///  and u.role_id &lt;&gt; 1.
        /// </summary>
        internal static string GetUserById {
            get {
                return ResourceManager.GetString("GetUserById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select u.id       as Id,
        ///       u.username as Username,
        ///       u.password as Password,
        ///       r.name     as Role,
        ///       c.id       as ClientId,
        ///       c.name     as Name,
        ///       c.address  as Address,
        ///       c.inn      as INN,
        ///       u.status   as Status
        ///from users u
        ///         join client c on c.id = u.client_id
        ///         join role r on r.id = u.role_id
        ///where u.role_id &lt;&gt; 1.
        /// </summary>
        internal static string GetUsers {
            get {
                return ResourceManager.GetString("GetUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT r.name AS Role,
        ///       count(1) as Count,
        ///       json_agg(json_build_object(
        ///               &apos;Id&apos;, u.id,
        ///               &apos;Username&apos;, u.username,
        ///               &apos;Password&apos;, u.password,
        ///               &apos;Role&apos;, r.name,
        ///               &apos;ClientId&apos;, c.id,
        ///               &apos;Name&apos;, c.name,
        ///               &apos;Address&apos;, c.address,
        ///               &apos;INN&apos;, c.inn,
        ///               &apos;Status&apos;, u.status
        ///                )) AS Users
        ///FROM users u
        ///    JOIN client c
        ///ON c.id = u.client_id
        ///    JOIN role r ON r.id = u.rol [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetUsersGroups {
            get {
                return ResourceManager.GetString("GetUsersGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update cart_item
        ///set quantity    = @quantity,
        ///    is_selected = @is_selected
        ///where id = @id;.
        /// </summary>
        internal static string UpdateCartItem {
            get {
                return ResourceManager.GetString("UpdateCartItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update image
        ///set url = @url
        ///where id = @id;.
        /// </summary>
        internal static string UpdateImage {
            get {
                return ResourceManager.GetString("UpdateImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update orders
        ///set status = @status
        ///where id = @id.
        /// </summary>
        internal static string UpdateOrder {
            get {
                return ResourceManager.GetString("UpdateOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update product
        ///set name   = @name,
        ///    status = @status,
        ///    price  = @price
        ///where id = @id;.
        /// </summary>
        internal static string UpdateProduct {
            get {
                return ResourceManager.GetString("UpdateProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update product_item
        ///set color  = @color,
        ///    size   = @size,
        ///    weight = @weight
        ///where id = @id;.
        /// </summary>
        internal static string UpdateProductItem {
            get {
                return ResourceManager.GetString("UpdateProductItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update users
        ///set status = @status
        ///where id = @id.
        /// </summary>
        internal static string UpdateUser {
            get {
                return ResourceManager.GetString("UpdateUser", resourceCulture);
            }
        }
    }
}
