//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Scripts {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Scripts {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Scripts() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Repository.Scripts.Scripts", typeof(Scripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AddCartItem {
            get {
                return ResourceManager.GetString("AddCartItem", resourceCulture);
            }
        }
        
        internal static string AddClient {
            get {
                return ResourceManager.GetString("AddClient", resourceCulture);
            }
        }
        
        internal static string AddImages {
            get {
                return ResourceManager.GetString("AddImages", resourceCulture);
            }
        }
        
        internal static string AddOperation {
            get {
                return ResourceManager.GetString("AddOperation", resourceCulture);
            }
        }
        
        internal static string AddOperationDetail {
            get {
                return ResourceManager.GetString("AddOperationDetail", resourceCulture);
            }
        }
        
        internal static string AddOrder {
            get {
                return ResourceManager.GetString("AddOrder", resourceCulture);
            }
        }
        
        internal static string AddOrderItem {
            get {
                return ResourceManager.GetString("AddOrderItem", resourceCulture);
            }
        }
        
        internal static string AddProduct {
            get {
                return ResourceManager.GetString("AddProduct", resourceCulture);
            }
        }
        
        internal static string AddProductItem {
            get {
                return ResourceManager.GetString("AddProductItem", resourceCulture);
            }
        }
        
        internal static string AddProductMaterials {
            get {
                return ResourceManager.GetString("AddProductMaterials", resourceCulture);
            }
        }
        
        internal static string AddUser {
            get {
                return ResourceManager.GetString("AddUser", resourceCulture);
            }
        }
        
        internal static string DeleteCartItem {
            get {
                return ResourceManager.GetString("DeleteCartItem", resourceCulture);
            }
        }
        
        internal static string DeleteProductMaterials {
            get {
                return ResourceManager.GetString("DeleteProductMaterials", resourceCulture);
            }
        }
        
        internal static string GenerateReport {
            get {
                return ResourceManager.GetString("GenerateReport", resourceCulture);
            }
        }
        
        internal static string GetAllOrders {
            get {
                return ResourceManager.GetString("GetAllOrders", resourceCulture);
            }
        }
        
        internal static string GetCartByUserId {
            get {
                return ResourceManager.GetString("GetCartByUserId", resourceCulture);
            }
        }
        
        internal static string GetCartItemByCartId {
            get {
                return ResourceManager.GetString("GetCartItemByCartId", resourceCulture);
            }
        }
        
        internal static string GetImagesByProductId {
            get {
                return ResourceManager.GetString("GetImagesByProductId", resourceCulture);
            }
        }
        
        internal static string GetOrdersByUserId {
            get {
                return ResourceManager.GetString("GetOrdersByUserId", resourceCulture);
            }
        }
        
        internal static string GetProductItemsByProductId {
            get {
                return ResourceManager.GetString("GetProductItemsByProductId", resourceCulture);
            }
        }
        
        internal static string GetProductMaterials {
            get {
                return ResourceManager.GetString("GetProductMaterials", resourceCulture);
            }
        }
        
        internal static string GetProducts {
            get {
                return ResourceManager.GetString("GetProducts", resourceCulture);
            }
        }
        
        internal static string GetUsers {
            get {
                return ResourceManager.GetString("GetUsers", resourceCulture);
            }
        }
        
        internal static string UpdateCartItem {
            get {
                return ResourceManager.GetString("UpdateCartItem", resourceCulture);
            }
        }
        
        internal static string UpdateImage {
            get {
                return ResourceManager.GetString("UpdateImage", resourceCulture);
            }
        }
        
        internal static string UpdateOrder {
            get {
                return ResourceManager.GetString("UpdateOrder", resourceCulture);
            }
        }
        
        internal static string UpdateProduct {
            get {
                return ResourceManager.GetString("UpdateProduct", resourceCulture);
            }
        }
        
        internal static string UpdateProductItem {
            get {
                return ResourceManager.GetString("UpdateProductItem", resourceCulture);
            }
        }
        
        internal static string UpdateUser {
            get {
                return ResourceManager.GetString("UpdateUser", resourceCulture);
            }
        }
        
        internal static string GetAllMaterials {
            get {
                return ResourceManager.GetString("GetAllMaterials", resourceCulture);
            }
        }
        
        internal static string CreateCart {
            get {
                return ResourceManager.GetString("CreateCart", resourceCulture);
            }
        }
        
        internal static string GetUserById {
            get {
                return ResourceManager.GetString("GetUserById", resourceCulture);
            }
        }
        
        internal static string GetProductItemByIds {
            get {
                return ResourceManager.GetString("GetProductItemByIds", resourceCulture);
            }
        }
        
        internal static string GetProductsByFactoryId {
            get {
                return ResourceManager.GetString("GetProductsByFactoryId", resourceCulture);
            }
        }
        
        internal static string GetUsersGroups {
            get {
                return ResourceManager.GetString("GetUsersGroups", resourceCulture);
            }
        }
    }
}
